name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # ou laisse vide pour latest stable

      - name: Install dependencies
        working-directory: byf_flutter_complete
        run: flutter pub get

      - name: Build APK
        working-directory: byf_flutter_complete
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: byf-release-apk
          path: byf_flutter_complete/build/app/outputs/flutter-apk/app-release.apk
